### ISSUE TITLE
About modifying the Reynolds numbers

### ISSUE THREAD

**Issue by Gwen-JW** [thw1021/Cylinder2DFlowControlGeneral#6]
Hi,

Thanks for your great work!

I get some trouble when I try to modify the Reynolds numbers. I want to train the control strategy under `Re = (1 * 0.1) / 0.0005 = 200`, so I adjust the parameter `mu` to `5E-4`. But when I try to make a new mesh, I find the drag is `nan`, like this:
![image](https://user-images.githubusercontent.com/79836881/134463344-6c4b0616-28bc-4e69-a760-94e9ead703b8.png)

Could you please help me solve this problem, or note me how to modify the `Re`? Cause I'm not very sure the modification is proper.

**Comment by jerabaul29** [comment]
That indicates that the simulation has diverged, due to problem with either the mesh size or the dt choice.

Re 200 should work fine with this config:

https://github.com/thw1021/Cylinder2DFlowControlGeneral/tree/master/RobustDRLCylinder2DControl/simulation_base/mesh_200

So should be possible to run using this script already:

https://github.com/thw1021/Cylinder2DFlowControlGeneral/blob/master/RobustDRLCylinder2DControl/Env2DCylinder.py

**Comment by jerabaul29** [comment]
you can also look at the doc on the "parent" repos:

https://github.com/jerabaul29/Cylinder2DFlowControlDRL

https://github.com/jerabaul29/Cylinder2DFlowControlDRLParallel

**Comment by Gwen-JW** [comment]
Thanks a lot. I'll try it later.

**Comment by Gwen-JW** [comment]
Thanks for your reply. I think I have solved this problem. I reset the dt, and it works now.

**Comment by jerabaul29** [comment]
Feel free to close if it does is solved :) .

**Comment by Gwen-JW** [comment]
Okay.
