### ISSUE TITLE
About ------- hit NaN in flow field variables in execute -------

### ISSUE THREAD

**Issue by ruyigolden-cudgel** [thw1021/Cylinder2DFlowControlGeneral#9]
Hello, @thw1021. 
&nbsp;&nbsp;&nbsp;&nbsp;I have noticed that a new function which is **_def found_invalid_values(to_check, **abs_threshold=300**)_** for detecting NaN values has been added to Env2dCylinder.py.It's really great with this fuction to get timely notifications and measures for problems in training. And i ran into a problem when i had started my training.
&nbsp;&nbsp;&nbsp;&nbsp;My multi-environment training with the information  _**------- hit NaN in flow field variables in execute -------**_ and then the training got reset. In troubleshooting the problem, I found that **self.probes_values**, which samples pressure, has exceeded  default threshold you set in which is **abs_threshold=300**. The **self.probes_values** reported in my training is between 468——470.
&nbsp;&nbsp;&nbsp;&nbsp;Could you please help with my problem? 
&nbsp;&nbsp;&nbsp;&nbsp;Q1:Is there any specific reason for this default threshold to set?
&nbsp;&nbsp;&nbsp;&nbsp;Q2:Will any new issues arise if the default threshold is CHANGED?
Thanks!

**Comment by thw1021** [comment]
Hi,

Thank you for your interest in our work.

To Q1: Since this work was finished a long time ago, I am really sorry that I do not remember the details of the setting. I think `abs_threshold=300` was used based on our experience (no special reason), and you can modify it at yours.
To Q2: I am not sure. You can have a try.

In summary, the present CFD solver is not very suitable for flows at higher Reynolds numbers. You can try some other CFD solver. For example, https://github.com/venturi123/DRLinFluids and https://github.com/npuljc/RL_control_Nek5000

Hope this answer helps.

Best

**Comment by ruyigolden-cudgel** [comment]
Thanks, but there is still one thing i want to make sure.
Is this threshold set to prevent agent  from taking actions to the enviroment state i don't want? Like the agent actions increase the drag around the cylinder or get flow field more unstable?

**Comment by thw1021** [comment]
If I remember correctly, this threshold is set to avoid too big values of jets, which could lead to the failure of flow simulations.

**Comment by ruyigolden-cudgel** [comment]
Thanks！It really helps
